services:
  portfolio:
    image: ghcr.io/realroem/media-portfolio:latest
    container_name: roem-portfolio
    restart: unless-stopped
    ports:
      - '127.0.0.1:8080:8080'

  watchtower:
    image: containrrr/watchtower:latest
    container_name: roem-watchtower
    restart: unless-stopped
    environment:
      DOCKER_API_VERSION: '1.44'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 60 roem-portfolio
